"""Generate the public, self-contained JSON Schema without third-party tools."""
import json
from pathlib import Path

def obj(properties):return {'type':'object','additionalProperties':False,'required':list(properties),'properties':properties}
nullable_text={'type':['string','null']};boolean={'type':'boolean'};nullable_number={'type':['number','null']};score={'type':['number','null'],'minimum':0,'maximum':1};free={'type':'object'}
metric=obj({'id':{'enum':['M1','M2']},'defined':boolean,'status':{'enum':['measured','unmeasurable','not_run','not_applicable','error']},'measurement_attempted':boolean,'judgment':{'enum':['physics_pass','physics_fail','task_failed','evidence_insufficient','not_applicable']},'raw_value':{},'unit':nullable_text,'physics_score':score,'pass_threshold':score,'reason':nullable_text,'principle':{'type':'string'},'measurement_steps':{'type':'array','items':{'type':'string'}},'measurements':{},'normalization':free,'uncertainty':{'type':['object','null']},'evidence':{'type':'array','items':free}})
metric['allOf']=[{'if':{'properties':{'status':{'const':'measured'}}},'then':{'properties':{'defined':{'const':True},'measurement_attempted':{'const':True},'physics_score':{'type':'number','minimum':0,'maximum':1},'raw_value':{'not':{'type':'null'}}}},'else':{'properties':{'physics_score':{'type':'null'},'raw_value':{'type':'null'}}}},{'if':{'properties':{'defined':{'const':False}}},'then':{'properties':{'status':{'const':'not_applicable'},'measurement_attempted':{'const':False}}}}]
schema=obj({'schema_version':{'const':'vdmbench.evaluation.v4'},'task':obj({'id':{'type':'string','pattern':'^P[0-9]+[a-z]?$'},'group':{'type':['string','null']},'difficulty':{'enum':['Easy','Medium','Hard']},'phenomenon':{'type':'string'},'domain':{'type':'string'}}),'sample':obj({'id':nullable_text,'model':nullable_text,'seed':{'type':['integer','null']},'video_path':{'type':'string'},'image_path':nullable_text,'video_prompt':nullable_text,'video_sha256':nullable_text,'image_sha256':nullable_text}),'status':{'enum':['complete','partial','unavailable','consistency_rejected','consistency_error','execution_error']},'consistency':obj({'status':{'type':'string'},'score':score,'threshold':score,'passed':{'type':['boolean','null']},'reason':nullable_text,'details':free}),'physics':obj({'attempted':boolean,'status':{'enum':['not_run','complete','partial','unavailable']},'score':score,'judgment':{'enum':['physics_pass','physics_fail','task_failed','evidence_insufficient']},'defined_metrics':{'type':'integer','minimum':0,'maximum':2},'measured_metrics':{'type':'integer','minimum':0,'maximum':2},'coverage':score,'missing_metric_policy':{'type':'string'},'reason':nullable_text}),'metrics':obj({'M1':{'$ref':'#/$defs/metric'},'M2':{'$ref':'#/$defs/metric'}}),'score':obj({'total':score,'consistency_weight':{'const':.15},'physics_weight':{'const':.85},'consistency_contribution':score,'physics_contribution':score,'formula':{'type':'string'}}),'failures':{'type':'array','items':obj({'stage':{'enum':['input','consistency','physics','schema']},'metric_id':{'enum':['M1','M2',None]},'code':{'type':'string'},'message':{'type':'string'}})},'provenance':free})
schema.update({'$schema':'https://json-schema.org/draft/2020-12/schema','$id':'urn:vdmbench:evaluation:v4','title':'VDMBench V4 evaluation result','$defs':{'metric':metric}})
schema['allOf']=[{'if':{'properties':{'status':{'enum':['execution_error','consistency_error']}}},'then':{'properties':{'score':{'properties':{'total':{'type':'null'}}}}}}]
Path(__file__).with_name('evaluation.v4.schema.json').write_text(json.dumps(schema,ensure_ascii=False,indent=2)+'\n')
